import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
